class SkillList:
    skills = ["--------","Attack Boost", "Agitator","Peak Performance", "Resentment", "Resuscitate",
    "Critical Eye","Weakness Exploit","Latent Power","Maximum Might","Critical Element",
    "Fire Attack","Water Attack","Ice Attack","Thunder Attack","Dragon Attack",
    "Poison Attack","Paralysis Attack","Sleep Attack","Blast Attack","Handicraft",
    "Razor Sharp","Spare Shot","Protective Polish","Mind's Eye","Ballistics","Bludegoner",
    "Focus","Power Prolonger","Marathon Runner","Constitution","Stamina Surge","Guard",
    "Guard Up","Offensive Guard","Critical Draw","Punishing Draw","Quick Sheathe",
    "Slugger","Stamina Thief","Affinity Sliding","Horn Maestro","Artillery","Load Shells",
    "Special Ammo Boost","Normal/Rapid Up","Pierce Up","Spread Up","Ammo Up",
    "Reload Speed","Recoil Down","Steadiness","Rapid Fire Up","Defense Boost",
    "Divine Blessing","Recovery Up","Recovery Speed","Speed Eating","Earplugs","Windproof",
    "Tremor Resistance","Bubbly Dance","Evade Window","Evade Extender","Fire Resistance",
    "Water Resistance","Ice Resistance","Thunder Resistance","Dragon Resistance",
    "Blight Resistance","Poison Resistance","Paralysis Resistance","Sleep Resistance",
    "Stun Resistance","Muck Resistance","Blast Resistance","Botanist","Geologist",
    "Partbreaker","Good Luck","Speed Sharpening","Bombardier","Mushroomancer",
    "Item Prolonger","Wide-Range","Free Meal","Heroics","Fortify","Flinch Free",
    "Carving Pro","Hunger Resistance","Leap of Faith","Diversion","Master Mounter",
    "Wirebug Whisperer","Wall Runner","Counterstrike","Rapid Morph","Hellfire Cloak",
    "Coalescence","Redirection","Spiribird's Call","Charge Master","Foray","Tune-Up",
    "Grinder (S)","Bladescale Hone","Wall Runner (Boost)","Chain Crit"]